#
# Automatically generated file
#

package Haiku::ApplicationKit;
use strict;
use warnings;
require Exporter;
require DynaLoader;

use Haiku::Handler;
use Haiku::Looper;
use Haiku::Application;
use Haiku::CustomApplication;
use Haiku::Clipboard;
use Haiku::Cursor;
use Haiku::Invoker;
use Haiku::Message;
use Haiku::Messenger;

our $VERSION = 0.01;
our @ISA = qw(DynaLoader Exporter);

my @commands_group = qw(B_SET_PROPERTY B_GET_PROPERTY B_CREATE_PROPERTY B_DELETE_PROPERTY B_COUNT_PROPERTIES B_EXECUTE_PROPERTY B_GET_SUPPORTED_SUITES B_UNDO B_REDO B_CUT B_COPY B_PASTE B_SELECT_ALL B_SAVE_REQUESTED B_MESSAGE_NOT_UNDERSTOOD B_NO_REPLY B_REPLY B_SIMPLE_DATA B_MIME_DATA B_ARCHIVED_OBJECT B_UPDATE_STATUS_BAR B_RESET_STATUS_BAR B_NODE_MONITOR B_QUERY_UPDATE B_ENDORSABLE B_COPY_TARGET B_MOVE_TARGET B_TRASH_TARGET B_LINK_TARGET B_INPUT_DEVICES_CHANGED B_INPUT_METHOD_EVENT B_WINDOW_MOVE_TO B_WINDOW_MOVE_BY B_SILENT_RELAUNCH B_OBSERVER_NOTICE_CHANGE B_CONTROL_INVOKED B_CONTROL_MODIFIED);
my @cursor_group = qw(B_CURSOR_SYSTEM_DEFAULT B_CURSOR_I_BEAM);
my @system_messages_group = qw(B_ABOUT_REQUESTED B_WINDOW_ACTIVATED B_APP_ACTIVATED B_ARGV_RECEIVED B_QUIT_REQUESTED B_CLOSE_REQUESTED B_CANCEL B_INVALIDATE B_KEY_DOWN B_KEY_UP B_UNMAPPED_KEY_DOWN B_UNMAPPED_KEY_UP B_LAYOUT_WINDOW B_MODIFIERS_CHANGED B_MINIMIZE B_MOUSE_DOWN B_MOUSE_MOVED B_MOUSE_ENTER_EXIT B_MOUSE_IDLE B_MOUSE_UP B_MOUSE_WHEEL_CHANGED B_OPEN_IN_WORKSPACE B_PRINTER_CHANGED B_PULSE B_READY_TO_RUN B_REFS_RECEIVED B_RELEASE_OVERLAY_LOCK B_ACQUIRE_OVERLAY_LOCK B_SCREEN_CHANGED B_VALUE_CHANGED B_TRANSLATOR_ADDED B_TRANSLATOR_REMOVED B_VIEW_MOVED B_VIEW_RESIZED B_WINDOW_MOVED B_WINDOW_RESIZED B_WORKSPACES_CHANGED B_WORKSPACE_ACTIVATED B_ZOOM _COLORS_UPDATED _FONTS_UPDATED _APP_MENU_ _BROWSER_MENUS_ _MENU_EVENT_ _PING_ _QUIT_ _VOLUME_MOUNTED_ _VOLUME_UNMOUNTED_ _MESSAGE_DROPPED_ _DISPOSE_DRAG_ _MENUS_DONE_ _SHOW_DRAG_HANDLES_ _EVENTS_PENDING_ _UPDATE_ _UPDATE_IF_NEEDED_ _PRINTER_INFO_ _SETUP_PRINTER_ _SELECT_PRINTER_);

our %EXPORT_TAGS = (
	commands => [@commands_group],
	cursor => [@cursor_group],
	system_messages => [@system_messages_group]
);
our @EXPORT_OK = (@commands_group, @cursor_group, @system_messages_group);

bootstrap Haiku::ApplicationKit $VERSION;

1;
