#
# Automatically generated file
#

package Haiku::Errors;
use strict;
use warnings;
require Exporter;

our $VERSION = 0.01;
our @ISA = qw(Exporter);

my @application_group = qw(B_BAD_REPLY B_DUPLICATE_REPLY B_MESSAGE_TO_SELF B_BAD_HANDLER B_ALREADY_RUNNING B_LAUNCH_FAILED B_AMBIGUOUS_APP_LAUNCH B_UNKNOWN_MIME_TYPE B_BAD_SCRIPT_SYNTAX B_LAUNCH_FAILED_NO_RESOLVE_LINK B_LAUNCH_FAILED_EXECUTABLE B_LAUNCH_FAILED_APP_NOT_FOUND B_LAUNCH_FAILED_APP_IN_TRASH B_LAUNCH_FAILED_NO_PREFERRED_APP B_LAUNCH_FAILED_FILES_APP_NOT_FOUND B_BAD_MIME_SNIFFER_RULE B_NOT_A_MESSAGE B_SHUTDOWN_CANCELLED B_SHUTTING_DOWN);
my @baselines_group = qw(B_GENERAL_ERROR_BASE B_OS_ERROR_BASE B_APP_ERROR_BASE B_INTERFACE_ERROR_BASE B_MEDIA_ERROR_BASE B_TRANSLATION_ERROR_BASE B_MIDI_ERROR_BASE B_STORAGE_ERROR_BASE B_POSIX_ERROR_BASE B_MAIL_ERROR_BASE B_PRINT_ERROR_BASE B_DEVICE_ERROR_BASE B_ERRORS_END);
my @device_group = qw(B_DEV_INVALID_IOCTL B_DEV_NO_MEMORY B_DEV_BAD_DRIVE_NUM B_DEV_NO_MEDIA B_DEV_UNREADABLE B_DEV_FORMAT_ERROR B_DEV_TIMEOUT B_DEV_RECALIBRATE_ERROR B_DEV_SEEK_ERROR B_DEV_ID_ERROR B_DEV_READ_ERROR B_DEV_WRITE_ERROR B_DEV_NOT_READY B_DEV_MEDIA_CHANGED B_DEV_MEDIA_CHANGE_REQUESTED B_DEV_RESOURCE_CONFLICT B_DEV_CONFIGURATION_ERROR B_DEV_DISABLED_BY_USER B_DEV_DOOR_OPEN B_DEV_INVALID_PIPE B_DEV_CRC_ERROR B_DEV_STALLED B_DEV_BAD_PID B_DEV_UNEXPECTED_PID B_DEV_DATA_OVERRUN B_DEV_DATA_UNDERRUN B_DEV_FIFO_OVERRUN B_DEV_FIFO_UNDERRUN B_DEV_PENDING B_DEV_MULTIPLE_ERRORS B_DEV_TOO_LATE);
my @general_group = qw(B_NO_MEMORY B_IO_ERROR B_PERMISSION_DENIED B_BAD_INDEX B_BAD_TYPE B_BAD_VALUE B_MISMATCHED_VALUES B_NAME_NOT_FOUND B_NAME_IN_USE B_TIMED_OUT B_INTERRUPTED B_WOULD_BLOCK B_CANCELED B_NO_INIT B_NOT_INITIALIZED B_BUSY B_NOT_ALLOWED B_BAD_DATA B_DONT_DO_THAT B_ERROR B_OK B_NO_ERROR);
my @kernel_group = qw(B_BAD_SEM_ID B_NO_MORE_SEMS B_BAD_THREAD_ID B_NO_MORE_THREADS B_BAD_THREAD_STATE B_BAD_TEAM_ID B_NO_MORE_TEAMS B_BAD_PORT_ID B_NO_MORE_PORTS B_BAD_IMAGE_ID B_BAD_ADDRESS B_NOT_AN_EXECUTABLE B_MISSING_LIBRARY B_MISSING_SYMBOL B_DEBUGGER_ALREADY_INSTALLED);
my @mail_group = qw(B_MAIL_NO_DAEMON B_MAIL_UNKNOWN_USER B_MAIL_WRONG_PASSWORD B_MAIL_UNKNOWN_HOST B_MAIL_ACCESS_ERROR B_MAIL_UNKNOWN_FIELD B_MAIL_NO_RECIPIENT B_MAIL_INVALID_MAIL);
my @media_group = qw(B_STREAM_NOT_FOUND B_SERVER_NOT_FOUND B_RESOURCE_NOT_FOUND B_RESOURCE_UNAVAILABLE B_BAD_SUBSCRIBER B_SUBSCRIBER_NOT_ENTERED B_BUFFER_NOT_AVAILABLE B_LAST_BUFFER_ERROR B_MEDIA_SYSTEM_FAILURE B_MEDIA_BAD_NODE B_MEDIA_NODE_BUSY B_MEDIA_BAD_FORMAT B_MEDIA_BAD_BUFFER B_MEDIA_TOO_MANY_NODES B_MEDIA_TOO_MANY_BUFFERS B_MEDIA_NODE_ALREADY_EXISTS B_MEDIA_BUFFER_ALREADY_EXISTS B_MEDIA_CANNOT_SEEK B_MEDIA_CANNOT_CHANGE_RUN_MODE B_MEDIA_APP_ALREADY_REGISTERED B_MEDIA_APP_NOT_REGISTERED B_MEDIA_CANNOT_RECLAIM_BUFFERS B_MEDIA_BUFFERS_NOT_RECLAIMED B_MEDIA_TIME_SOURCE_STOPPED B_MEDIA_TIME_SOURCE_BUSY B_MEDIA_BAD_SOURCE B_MEDIA_BAD_DESTINATION B_MEDIA_ALREADY_CONNECTED B_MEDIA_NOT_CONNECTED B_MEDIA_BAD_CLIP_FORMAT B_MEDIA_ADDON_FAILED B_MEDIA_ADDON_DISABLED B_MEDIA_CHANGE_IN_PROGRESS B_MEDIA_STALE_CHANGE_COUNT B_MEDIA_ADDON_RESTRICTED B_MEDIA_NO_HANDLER B_MEDIA_DUPLICATE_FORMAT B_MEDIA_REALTIME_DISABLED B_MEDIA_REALTIME_UNAVAILABLE);
my @posix_group = qw(B_POSIX_ENOMEM E2BIG ECHILD EDEADLK EFBIG EMLINK ENFILE ENODEV ENOLCK ENOSYS ENOTTY ENXIO ESPIPE ESRCH EFPOS ESIGPARM EDOM ERANGE EPROTOTYPE EPROTONOSUPPORT EPFNOSUPPORT EAFNOSUPPORT EADDRINUSE EADDRNOTAVAIL ENETDOWN ENETUNREACH ENETRESET ECONNABORTED ECONNRESET EISCONN ENOTCONN ESHUTDOWN ECONNREFUSED EHOSTUNREACH ENOPROTOOPT ENOBUFS EINPROGRESS EALREADY EILSEQ ENOMSG ESTALE EOVERFLOW EMSGSIZE EOPNOTSUPP ENOTSOCK EHOSTDOWN EBADMSG ECANCELED EDESTADDRREQ EDQUOT EIDRM EMULTIHOP ENODATA ENOLINK ENOSR ENOSTR ENOTSUP EPROTO ETIME ETXTBSY ENOATTR ENOMEM EACCES EINTR EIO EBUSY EFAULT ETIMEDOUT EAGAIN EWOULDBLOCK EBADF EEXIST EINVAL ENAMETOOLONG ENOENT EPERM ENOTDIR EISDIR ENOTEMPTY ENOSPC EROFS EMFILE EXDEV ELOOP ENOEXEC EPIPE B_BUFFER_OVERFLOW B_TOO_MANY_ARGS B_FILE_TOO_LARGE B_RESULT_NOT_REPRESENTABLE B_DEVICE_NOT_FOUND B_NOT_SUPPORTED);
my @printing_group = qw(B_NO_PRINT_SERVER);
my @storage_group = qw(B_FILE_ERROR B_FILE_NOT_FOUND B_FILE_EXISTS B_ENTRY_NOT_FOUND B_NAME_TOO_LONG B_NOT_A_DIRECTORY B_DIRECTORY_NOT_EMPTY B_DEVICE_FULL B_READ_ONLY_DEVICE B_IS_A_DIRECTORY B_NO_MORE_FDS B_CROSS_DEVICE_LINK B_LINK_LIMIT B_BUSTED_PIPE B_UNSUPPORTED B_PARTITION_TOO_SMALL);
my @translation_group = qw(B_TRANSLATION_BASE_ERROR B_NO_TRANSLATOR B_ILLEGAL_DATA);

our %EXPORT_TAGS = (
	application => [@application_group],
	baselines => [@baselines_group],
	device => [@device_group],
	general => [@general_group],
	kernel => [@kernel_group],
	mail => [@mail_group],
	media => [@media_group],
	posix => [@posix_group],
	printing => [@printing_group],
	storage => [@storage_group],
	translation => [@translation_group]
);
our @EXPORT_OK = (@application_group, @baselines_group, @device_group, @general_group, @kernel_group, @mail_group, @media_group, @posix_group, @printing_group, @storage_group, @translation_group);

1;
