#
# Automatically generated file
#

package Haiku::TypeConstants;
use strict;
use warnings;
require Exporter;

our $VERSION = 0.01;
our @ISA = qw(Exporter);

my @types_group = qw(B_AFFINE_TRANSFORM_TYPE B_ALIGNMENT_TYPE B_ANY_TYPE B_ATOM_TYPE B_ATOMREF_TYPE B_BOOL_TYPE B_CHAR_TYPE B_COLOR_8_BIT_TYPE B_DOUBLE_TYPE B_FLOAT_TYPE B_GRAYSCALE_8_BIT_TYPE B_INT16_TYPE B_INT32_TYPE B_INT64_TYPE B_INT8_TYPE B_LARGE_ICON_TYPE B_MEDIA_PARAMETER_GROUP_TYPE B_MEDIA_PARAMETER_TYPE B_MEDIA_PARAMETER_WEB_TYPE B_MESSAGE_TYPE B_MESSENGER_TYPE B_MIME_TYPE B_MINI_ICON_TYPE B_MONOCHROME_1_BIT_TYPE B_OBJECT_TYPE B_OFF_T_TYPE B_PATTERN_TYPE B_POINTER_TYPE B_POINT_TYPE B_PROPERTY_INFO_TYPE B_RAW_TYPE B_RECT_TYPE B_REF_TYPE B_RGB_32_BIT_TYPE B_RGB_COLOR_TYPE B_SIZE_TYPE B_SIZE_T_TYPE B_SSIZE_T_TYPE B_STRING_TYPE B_TIME_TYPE B_UINT16_TYPE B_UINT32_TYPE B_UINT64_TYPE B_UINT8_TYPE B_VECTOR_ICON_TYPE B_XATTR_TYPE B_NETWORK_ADDRESS_TYPE B_ASCII_TYPE);
my @url_types_group = qw(B_URL_HTTP B_URL_HTTPS B_URL_FTP B_URL_GOPHER B_URL_MAILTO B_URL_NEWS B_URL_NNTP B_URL_TELNET B_URL_RLOGIN B_URL_TN3270 B_URL_WAIS B_URL_FILE);

our %EXPORT_TAGS = (
	types => [@types_group],
	url_types => [@url_types_group]
);
our @EXPORT_OK = (@types_group, @url_types_group);

1;
